language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.5.12
install:
    - pip install -r requirements.txt
    - pip install -q Django==$DJANGO_VERSION
script:
    - flake8 .
notifications:
    email:
        - rajat.gupta712@gmail.com
